server {
  listen 80;
  server_name _;
  resolver 127.0.0.11 ipv6=off valid=10s;

  location /api/ {
    set $backend_upstream http://backend:9000;
    proxy_pass $backend_upstream;
  }

  location /admin/ {
    set $backend_upstream http://backend:9000;
    proxy_pass $backend_upstream;
  }

  location / {
    set $frontend_upstream http://frontend:3000;
    proxy_pass $frontend_upstream;
  }
}
